// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLSinhVien_CodeFirst.Data;

#nullable disable

namespace QLSinhVien_CodeFirst.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20240420051120_seeddata")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLSinhVien_CodeFirst.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");

                    b.HasData(
                        new
                        {
                            MaKhoa = 1,
                            TenKhoa = "CNTT"
                        },
                        new
                        {
                            MaKhoa = 2,
                            TenKhoa = "Điện - điện tử"
                        },
                        new
                        {
                            MaKhoa = 3,
                            TenKhoa = "Hóa"
                        },
                        new
                        {
                            MaKhoa = 4,
                            TenKhoa = "Xây dựng"
                        });
                });

            modelBuilder.Entity("QLSinhVien_CodeFirst.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GVCN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<int>("Siso")
                        .HasColumnType("int");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Lops");

                    b.HasData(
                        new
                        {
                            MaLop = "21T3",
                            GVCN = "Nguyen Văn Phát",
                            MaKhoa = 1,
                            Siso = 40
                        },
                        new
                        {
                            MaLop = "21T2",
                            GVCN = "Nguyễn Thị Hà Quyên",
                            MaKhoa = 1,
                            Siso = 40
                        },
                        new
                        {
                            MaLop = "21T1",
                            GVCN = "Trần Bửu Dung",
                            MaKhoa = 1,
                            Siso = 40
                        });
                });

            modelBuilder.Entity("QLSinhVien_CodeFirst.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSV = "21115053120326",
                            Diachi = "Thừa Thiên Huế",
                            Hoten = "Trương Văn Lâm",
                            MaLop = "21T3"
                        },
                        new
                        {
                            MaSV = "21115053120333",
                            Diachi = "Quảng Bình",
                            Hoten = "Trần Công Quang Phú",
                            MaLop = "21T3"
                        },
                        new
                        {
                            MaSV = "21115053120309",
                            Diachi = "Quảng Trị",
                            Hoten = "Lê Phước Đức",
                            MaLop = "21T3"
                        },
                        new
                        {
                            MaSV = "21115053120312",
                            Diachi = "Quảng Nam",
                            Hoten = "Phạm Thanh Trúc",
                            MaLop = "21T3"
                        });
                });

            modelBuilder.Entity("QLSinhVien_CodeFirst.Models.Lop", b =>
                {
                    b.HasOne("QLSinhVien_CodeFirst.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QLSinhVien_CodeFirst.Models.SinhVien", b =>
                {
                    b.HasOne("QLSinhVien_CodeFirst.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });
#pragma warning restore 612, 618
        }
    }
}
